
export const sample_foods: any[] = [
  {
    id:'1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 100,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/food-1.jpg',
    tags: ['FastFood', 'Pizza'],
  },
  {
    id:'2',
    name: 'Meatball',
    price: 150,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: 'assets/food-2.jpg',
    tags: ['FastFood'],
  },
  {
    id:'3',
    name: 'Hamburger',
    price: 149,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'assets/food-3.jpg',
    tags: ['FastFood'],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 110,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'assets/food-4.jpg',
    tags: ['FastFood'],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 99,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'assets/food-5.jpg',
    tags: ['FastFood'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 220,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/food-6.jpg',
    tags: ['FastFood'],
  },
  {
    id:'7',
    name: 'Mutton Biryani',
    price: 320,
    cookTime: '40-50',
    favorite: true,
    origins: ['India'],
    stars: 4.0,
    imageUrl: 'assets/muttonbiryani.jpg',
    tags: ['Biryani'],
  },
  {
    id:'8',
    name: 'Chicken Biryani',
    price: 250,
    cookTime: '30-40',
    favorite: true,
    origins: ['Indian'],
    stars: 4.0,
    imageUrl: 'assets/chickenbiryani.jpg',
    tags: ['Biryani'],
  },
  {
    id:'9',
    name: 'Egg Biryani',
    price: 199,
    cookTime: '25-30',
    favorite: false,
    origins: ['Indian'],
    stars: 4.0,
    imageUrl: 'assets/eggbiryani.jpg',
    tags: ['Biryani'],
  }
]

export const sample_tags:any[] = [
  { name: 'All', count: 9 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },,
  { name: 'biryani', count: 3 }
 
]

export const sample_users: any[] = [
  {
    name: "John Doe",
    email: "john@gmail.com",
    password: "12345",
    address: "Toronto On",
    isAdmin: true,
  },
  {
    name: "Jane Doe",
    email: "Jane@gmail.com",
    password: "12345",
    address: "Shanghai",
    isAdmin: false,
  },
];